name: Build and Deploy
on:
  push:
    branches:
    - main
jobs:
  build-deploy:
  name: Build and Deploy
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Install and setup JDK
    user: actions/setup-java@v2
    with:
      distribution: 'corretto'
      java-version: '17'
  - name: Unit Tests
    run: mvn -B test --file pom.xml
  - name: Build
    run: |
      mvn clean
      mvn -B package --file pom.xml
