apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: devopsinaction
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    nodePort: 31006
  selector:
    app: result

