apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapptwo
  name: webapptwo-svc
#  namespace: webapptwo-ns
spec:
  ports:
  - name: webapptwo-ports
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapptwo
  type: NodePort
