apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoapp
  name: demoapp-svc
  namespace: webhookns
spec:
  ports:
  - name: demoapp-ports
    nodePort: 31020
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demoapp
  type: NodePort
